if(NOT DEFINED _MM_GNU_CLANG_COMPILER_OPTIONS)
    set(_MM_GNU_CLANG_COMPILER_OPTIONS -Wall -Wextra -Wpedantic -Werror)
endif()

if(NOT DEFINED _MM_MSVC_COMPILER_OPTIONS)
    set(_MM_MSVC_COMPILER_OPTIONS /W4 /WX /permissive-)
endif()

if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    set(MATHSMERISE_COMPILER_OPTIONS ${_MM_GNU_CLANG_COMPILER_OPTIONS})
elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    set(MATHSMERISE_COMPILER_OPTIONS ${_MM_MSVC_COMPILER_OPTIONS})
endif()
